volumes:
  styles:
    name: tileserver-gl-style

networks:
  default:

services:
  tileserver-gl-styles:
    image: "ttungbmt/tileserver-gl-styles:latest"
    volumes:
      - styles:/data
    networks:
      - default

  tileserver-gl:
    image: "maptiler/tileserver-gl:latest"
    ports:
      - "8585:8080"
    command:
      - --port
      - "8080"
      - --config
      - "/data/config.json"
      # - --public_url
      # - "https://maptiler.laragis.vn"
      # - --verbose
    volumes:
      - styles:/data
      - ./mbtiles:/data/data
      - ./config/config.json:/data/config.json
    networks:
      - default
